top_100_men = ['kristian-blummenfelt', 'gustav-iden', 'magnus-elbaek-ditlev', 'sam-laidlow', 'max-neumann', 'sam-long',
               'leon-chevalier', 'aaron-royle', 'daniel-baekkegard', 'ben-kanute', 'pieter-heemeryck', 'frederic-funk',
               'patrick-lange', 'lionel-sanders', 'florian-angert', 'denis-chevrot', 'jason-west', 'clement-mignon',
               'kristian-hogenhaug', 'joe-skipper', 'miki-moerck-taagholt', 'alistair-brownlee', 'bradley-weiss',
               'mathis-margirier', 'jackson-laundry', 'rudy-von-berg', 'sebastian-kienle', 'thomas-bishop', 'matt-hanson',
               'mathias-lyngsoe', 'gregory-barnaby', 'pablo-dapena', 'trevor-foley', 'braden-currie', 'kyle-smith',
               'david-mcnamee', 'thor-bendix', 'robert-wilkowiecki', 'antonio-benito', 'cameron-wurf', 'youri-keulen',
               'josh-amberger', 'steven-mckenna', 'bart-aernouts', 'robert-kallin', 'pierre-le', 'james-teagle',
               'menno-koolhaas', 'chris-leiferman', 'filipe-azevedo', 'ondrej-kubo', 'cody-beals', 'christophe-de',
               'luciano-taccone', 'arnaud-guilloux', 'tomas-rodriguez', 'kacper-stepniak', 'matt-trautman',
               'mike-phillips', 'jan-stratmann', 'jesper-svensson', 'timothy-o', 'william-mennesson', 'rico-bogen',
               'franz-loeschke', 'matthew-sharpe', 'niek-heldoorn', 'justin-metzler', 'alessandro-fabian',
               'ognjen-stojanovi', 'kieran-lindars', 'brent-mcmahon', 'dylan-magnien', 'lukas-kocar', 'simon-viain',
               'arthur-horseau', 'matthew-mcelroy', 'andrea-salvisberg', 'jack-moody', 'tristan-olij', 'michael-weiss',
               'marc-dubrick', 'thomas-steger', 'antony-costes', 'nicholas-free', 'andrew-starykowicz',
               'reinaldo-colucci', 'dominik-sowieja', 'maurice-clavel', 'fabian-reuter', 'tim-van', 'mitchell-kibby',
               'ruben-zepuntke', 'adriano-engelhardt', 'fernando-toldi', 'tom-hug', 'kyle-buckingham', 'caleb-noble',
               'ivan-tutukin', 'jordi-montraveta']
